/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class ManagerPortal extends javax.swing.JFrame {

    /**
     * Creates new form AdamProfile
     */
    public ManagerPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Employees = new javax.swing.JButton();
        Books_View = new javax.swing.JButton();
        Excercise = new javax.swing.JButton();
        Batch_Details = new javax.swing.JButton();
        Customers = new javax.swing.JButton();
        Fees = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Add_Employee = new javax.swing.JButton();
        Add_Book = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Add_Program = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Manager Portal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        Employees.setBackground(new java.awt.Color(0, 0, 0));
        Employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.png"))); // NOI18N
        Employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeesActionPerformed(evt);
            }
        });
        jPanel1.add(Employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 140, 100));

        Books_View.setBackground(new java.awt.Color(0, 0, 0));
        Books_View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book.png"))); // NOI18N
        Books_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Books_ViewActionPerformed(evt);
            }
        });
        jPanel1.add(Books_View, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, 120));

        Excercise.setBackground(new java.awt.Color(0, 0, 0));
        Excercise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/weight.png"))); // NOI18N
        Excercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcerciseActionPerformed(evt);
            }
        });
        jPanel1.add(Excercise, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 100));

        Batch_Details.setBackground(new java.awt.Color(0, 0, 0));
        Batch_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/batch.png"))); // NOI18N
        Batch_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batch_DetailsActionPerformed(evt);
            }
        });
        jPanel1.add(Batch_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 140, 100));

        Customers.setBackground(new java.awt.Color(0, 0, 0));
        Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customer.png"))); // NOI18N
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });
        jPanel1.add(Customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 140, 120));

        Fees.setBackground(new java.awt.Color(0, 0, 0));
        Fees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fees.png"))); // NOI18N
        Fees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeesMouseClicked(evt);
            }
        });
        Fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeesActionPerformed(evt);
            }
        });
        jPanel1.add(Fees, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 140, 120));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 245));
        jLabel3.setText("Excercises");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, 20));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setText("Employees");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 120, -1));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setText("Batch Details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 245, 245));
        jLabel6.setText("Books ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 245, 245));
        jLabel7.setText("Customers");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 245, 245));
        jLabel8.setText("Fees");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        Back_Button.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        Back_Button.setForeground(new java.awt.Color(245, 245, 245));
        Back_Button.setText("< Back");
        Back_Button.setContentAreaFilled(false);
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 120, 30));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MANAGE EMPLOYEES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 240, -1));

        Add_Employee.setBackground(new java.awt.Color(0, 0, 0));
        Add_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/person-circle-plus.png"))); // NOI18N
        Add_Employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_EmployeeMouseClicked(evt);
            }
        });
        jPanel1.add(Add_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 140, 100));
        Add_Book.setBackground(new java.awt.Color(0, 0, 0));
        Add_Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/books-medical.png"))); // NOI18N
        Add_Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_BookMouseClicked(evt);
            }
        });
        jPanel1.add(Add_Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 130, 100));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ADD BOOKS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 130, 20));

        Add_Program.setBackground(new java.awt.Color(0, 0, 0));
        Add_Program.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar-check.png"))); // NOI18N
        Add_Program.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_ProgramMouseClicked(evt);
            }
        });
        jPanel1.add(Add_Program, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 130, 90));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADD PROGRAMS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 569,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmployeesActionPerformed
        EmployeeProfiles EmployeeProfilesFrame = new EmployeeProfiles();
        EmployeeProfilesFrame.setVisible(true);
        EmployeeProfilesFrame.pack();
        EmployeeProfilesFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_EmployeesActionPerformed

    private void Books_ViewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Books_ViewActionPerformed
        BookDetails BookDetailsFrame = new BookDetails();
        BookDetailsFrame.setVisible(true);
        BookDetailsFrame.pack();
        BookDetailsFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Books_ViewActionPerformed

    private void ExcerciseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ExcerciseActionPerformed
        Exercises ExercisesFrame = new Exercises();
        ExercisesFrame.setVisible(true);
        ExercisesFrame.pack();
        ExercisesFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_ExcerciseActionPerformed

    private void Batch_DetailsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Batch_DetailsActionPerformed
        BatchDetails BatchDetailsFrame = new BatchDetails();
        BatchDetailsFrame.setVisible(true);
        BatchDetailsFrame.pack();
        BatchDetailsFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_Batch_DetailsActionPerformed

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CustomersActionPerformed
        Customers CustomersFrame = new Customers();
        CustomersFrame.setVisible(true);
        CustomersFrame.pack();
        CustomersFrame.setLocationRelativeTo(null);
        this.dispose(); // TODO add your handling code here:
    }// GEN-LAST:event_CustomersActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Back_ButtonActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }// GEN-LAST:event_Back_ButtonActionPerformed

    private void FeesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FeesActionPerformed
        Fees FeesFrame = new Fees();
        FeesFrame.setVisible(true);
        FeesFrame.pack();
        FeesFrame.setLocationRelativeTo(null);
        this.dispose();
    }// GEN-LAST:event_FeesActionPerformed

    private void Add_BookMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Add_BookMouseClicked
        // Todo add your handling code here:
        new Add_Booking().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_Add_BookMouseClicked

    private void Add_ProgramMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Add_ProgramMouseClicked
        // Todo add your handling code here:
        new Add_Program().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_Add_ProgramMouseClicked

    private void Add_EmployeeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_Add_EmployeeMouseClicked
        // Todo add your handling code here:
        new Add_Employee().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_Add_EmployeeMouseClicked



    private void FeesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_FeesMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_FeesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Book;
    private javax.swing.JButton Add_Employee;
    private javax.swing.JButton Add_Program;
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Batch_Details;
    private javax.swing.JButton Books_View;
    private javax.swing.JButton Customers;
    private javax.swing.JButton Employees;
    private javax.swing.JButton Excercise;
    private javax.swing.JButton Fees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}